-- 코드를 입력하세요
WITH MILK AS(
    SELECT CART_ID, NAME
    FROM CART_PRODUCTS
    WHERE NAME LIKE '%Milk%'
)
    
    
SELECT P.CART_ID
FROM CART_PRODUCTS P
RIGHT JOIN MILK M
ON P.CART_ID = M.CART_ID
WHERE P.NAME LIKE '%Yogurt%'
GROUP BY P.CART_ID
ORDER BY CART_ID ASC;