WITH EMP AS (
    SELECT EMP_NO, EMP_NAME, POSITION, EMAIL
    FROM HR_EMPLOYEES
    GROUP BY EMP_NO)

SELECT SUM(SCORE) AS SCORE , E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_GRADE G
RIGHT JOIN EMP E
ON G.EMP_NO =E.EMP_NO
GROUP BY E.EMP_NO
ORDER BY SCORE DESC
LIMIT 1;


